### ISSUE TITLE
M2 test fails both algorithms

### ISSUE THREAD

**Issue by abruck1** [ericaddison/UT-Social-Computing#4]
For some reason DGS thinks the max answer is 292.
KM throws a IllegalStateException.

I tried to model this in Gurobi to see if the TA has a mistake in the max (should be 293) but I have not been successful.

**Comment by abruck1** [comment]
I got gurobi working and indeed 293 is the answer with this matching:
(1, 12)
(2, 27)
(3, 25)
(4, 14)
(5, 9)
(6, 30)
(7, 1)
(8, 26)
(9, 16)
(10, 20)
(11, 17)
(12, 6)
(13, 7)
(14, 10)
(15, 15)
(16, 5)
(17, 28)
(18, 29)
(19, 3)
(20, 8)
(21, 2)
(22, 4)
(23, 24)
(24, 11)
(25, 19)
(26, 22)
(27, 21)
(28, 23)
(29, 13)
(30, 18)

**Comment by ericaddison** [comment]
Well, I fixed the exception in KM, but it gets the wrong answer! 274 :(

**Comment by ericaddison** [comment]
OK, KM is fixed. I pushed it straight up to master, so do a pull :)

**Comment by abruck1** [comment]
I found a fix for mine, but I still need to prove to myself why it works. It has to do with a rounding error and the Math.ceil call on the price. In any case, I am going to add the gurobi python code to the repo for funsies in case we get another failure and we need a solution.

**Comment by abruck1** [comment]
OK, I proved to myself why this was needed. Although the weights must be integers, the price MUST be type double. This is to properly account for increases in price. Test M2 exposes this because multiple bidders have the same weight for the same item. If only 2 bidders contended for the price then when Math.ceil was called it was enough to differentiate between the two. When >2 bidders with same weight exist then we must increase delta multiple times without erroneously pricing the bidders out.

Test now passes. Looks like this is done. As mentioned before, the gurobi code is in the resources directory. It cannot run (needs gurobi package/license/etc.) but this way we have the source code to expose the best matching using simplex algorithm.
